In [2]:
import pandas as pd
from sklearn import datasets

In [3]:
readfile = pd.read_excel(r"C:\Users\175045\Amit Python\File handling with Pandas\Steps.xlsx")
iris = datasets.load_iris()

In [7]:
readfile.head()

,Steps,Task,Comments
0,1.0,Prepare NDD and submit it for TPR review and r...,NaN
1,NaN,NaN,NaN
2,2.0,Submit the NDD after TPR approval in NSDP portal.,Change can be raise in prior to NSDR approval
3,NaN,NaN,NaN
4,3.0,raise request for DNS and add device in Netinfo,NaN

In [6]:
readfile.columns

Index(['Steps', 'Task', 'Comments'], dtype='object')

In [9]:
RemovedNA = readfile.dropna()

,Steps,Task,Comments
2,2.0,Submit the NDD after TPR approval in NSDP portal.,Change can be raise in prior to NSDR approval
6,4.0,Lock Down the chanage by Friday,If we are planning for the change to go on nex...

In [12]:
readfile.index

RangeIndex(start=0, stop=25, step=1)

In [17]:
readfile.iloc[1:10, 2:]

                                            Comments
1                                                NaN
2      Change can be raise in prior to NSDR approval
3                                                NaN
4                                                NaN
5                                                NaN
6  If we are planning for the change to go on nex...
7                                                NaN
8                                                NaN
9                                                NaN

In [22]:
readfile.values

array([[1.0,
        'Prepare NDD and submit it for TPR review and review held from by Monday',
        nan],
       [nan, nan, nan],
       [2.0, 'Submit the NDD after TPR approval in NSDP portal.',
        'Change can be raise in prior to NSDR approval'],
       [nan, nan, nan],
       [3.0, 'raise request for DNS and add device in Netinfo', nan],
       [nan, nan, nan],
       [4.0, 'Lock Down the chanage by Friday',
        'If we are planning for the change to go on next weekends'],
       [nan, nan, nan],
       [5.0, 'Add change in NPMS and get it approved by Friday', nan],
       [nan, nan, nan],
       [6.0,
        'Send the cabling sheet to DCSD and ask for console and temporary access',
        nan],
       [nan, nan, nan],
       [7.0,
        "Get the change approved in the calls\nNAM-Tuesday Call only, 9:30PM\nAPAC-  James's call Monday @1:00PM, Wednesday@7:30AM & 12:30PM",
        nan],
       [nan, nan, nan],
       [8.0,
        'Get it approved all the change task as well as for group task',
        nan],
       [nan, nan, nan],
       [9.0, 'Once change is approved. Send the pre notification', nan],
       [nan, nan, nan],
       [10.0,
        'Get it implemented as per the change and take pre and post checks',
        nan],
       [nan, nan, nan],
       [11.0,
        'Once change is completed, send the post notification, check DNS entry',
        nan],
       [nan, nan, nan],
       [12.0, 'Close the change and update the NPMS', nan],
       [nan, nan, nan],
       [13.0, 'Close the project in NPMS', nan]], dtype=object)

In [24]:
readfile.transpose()

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
Steps,1,NaN,2,NaN,3,NaN,4,NaN,5,NaN,...,NaN,9,NaN,10,NaN,11,NaN,12,NaN,13
Task,Prepare NDD and submit it for TPR review and r...,NaN,Submit the NDD after TPR approval in NSDP portal.,NaN,raise request for DNS and add device in Netinfo,NaN,Lock Down the chanage by Friday,NaN,Add change in NPMS and get it approved by Friday,NaN,...,NaN,Once change is approved. Send the pre notifica...,NaN,Get it implemented as per the change and take ...,NaN,"Once change is completed, send the post notifi...",NaN,Close the change and update the NPMS,NaN,Close the project in NPMS
Comments,NaN,NaN,Change can be raise in prior to NSDR approval,NaN,NaN,NaN,If we are planning for the change to go on nex...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
readtemp = pd.read_excel(r"C:\Users\175045\Desktop\Extra.xlsx")

In [29]:
readtemp

    Night Shift  1st  2nd   3rd  4th  5th  Unnamed: 6
0           Jan   26   NaN  NaN  NaN  NaN         NaN
1           Feb    2     9  NaN  NaN  NaN         NaN
2         March  NaN   NaN  NaN  NaN  NaN         NaN
3         April    7    14  NaN  NaN  NaN         NaN
4           May   26   NaN  NaN  NaN  NaN         NaN
5          June    8    22   29  NaN  NaN         NaN
6          July    6    13   14   20  NaN         NaN
7        August    3     4   10   17   18         NaN
8     September   21    28   29  NaN  NaN         NaN
9           Oct   19    22   26  NaN  NaN         NaN
10          Nov    3     9   10   16  NaN         NaN
11         2020  NaN   NaN  NaN  NaN  NaN         NaN
12  Night Shift  1st  2nd   3rd  4th  5th         NaN
13          Jan   11    25  NaN  NaN  NaN         NaN
14          Feb    1    16  NaN  NaN  NaN         NaN
15        March    7     8   14   15   21        29.0
16        April    4    11   26  NaN  NaN         NaN
17          May    3    24  NaN  NaN  NaN         NaN
18         June    6    13  NaN  NaN  NaN         NaN
19         July  NaN   NaN  NaN  NaN  NaN         NaN
20       August  NaN   NaN  NaN  NaN  NaN         NaN
21    September  NaN   NaN  NaN  NaN  NaN         NaN
22          Oct  NaN   NaN  NaN  NaN  NaN         NaN
23          Nov  NaN   NaN  NaN  NaN  NaN         NaN

In [36]:
readtemp.dropna()

   Night Shift 1st 2nd  3rd 4th 5th  Unnamed: 6
15       March   7    8  14  15  21        29.0

In [39]:
readtemp.keys()

Index(['Night Shift', '1st', '2nd ', '3rd', '4th', '5th', 'Unnamed: 6'], dtype='object')

In [43]:
sheet_read = pd.read_excel(r"C:\Users\175045\Desktop\Extra.xlsx", sheet_name="Comp Off")

In [44]:
sheet_read

,CHG NUM,WS#,Title,Start date (GMT),End date,Leave date
0,CHG0003540570,WS57696394.3,Taiwan Upgrade,17/08/2019 16:00,19/08/2019 02:00,9th Dec
1,CHG0003735502,WS65334120.22,Greece SRX to CP replacement,2019-03-11 05:00:00,2019-03-11 15:00:00,10th Dec
2,CHG0003802076,WS65717024,Korea CGMK firewall connectivity change,2019-09-11 05:00:00,16/11/2019 17:00,11th Dec
3,CHG0003827606,WS65717024,Korea CGMK CEP Firewall deployment,16/11/2019 4:30,16/11/2019 14:00,12th Dec
4,CHG0003637891,WS65759394.19,Korea JA86 Upgrade,16/11/2019 15:00,16/11/2019 19:00,NaN